package Frames;

import Controllers.ProductController;
import Controllers.StorageController;
import DB.DBManager;
import Entity.Product;
import Entity.Storage;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.swing.table.DefaultTableCellHeaderRenderer;

/**
 *
 * @author Tanya
 */
public class MainFrame extends javax.swing.JFrame {
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogConnection = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ConnectionOK = new javax.swing.JButton();
        tfURL = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        tfPassword = new javax.swing.JTextField();
        jDialogAddProduct = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        btnAddProduct = new javax.swing.JButton();
        tfAddNameProduct = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfAddCostProduct = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfAddCountProduct = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbAddProductIdStorage = new javax.swing.JComboBox<>();
        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Label = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        BtnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemStorage = new javax.swing.JMenuItem();
        menuItemProduct = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        jDialogConnection.setBounds(new java.awt.Rectangle(0, 0, 500, 300));

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        ConnectionOK.setText("OK");
        ConnectionOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectionOKActionPerformed(evt);
            }
        });

        tfURL.setText("jdbc:postgresql://localhost:5432/storage");

        tfName.setText("postgres");

        tfPassword.setText("1");

        javax.swing.GroupLayout jDialogConnectionLayout = new javax.swing.GroupLayout(jDialogConnection.getContentPane());
        jDialogConnection.getContentPane().setLayout(jDialogConnectionLayout);
        jDialogConnectionLayout.setHorizontalGroup(
            jDialogConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogConnectionLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(ConnectionOK, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(377, Short.MAX_VALUE))
            .addGroup(jDialogConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogConnectionLayout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addGroup(jDialogConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1))
                    .addGap(34, 34, 34)
                    .addGroup(jDialogConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfPassword)
                        .addComponent(tfName)
                        .addComponent(tfURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(280, Short.MAX_VALUE)))
        );
        jDialogConnectionLayout.setVerticalGroup(
            jDialogConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogConnectionLayout.createSequentialGroup()
                .addContainerGap(420, Short.MAX_VALUE)
                .addComponent(ConnectionOK)
                .addContainerGap())
            .addGroup(jDialogConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogConnectionLayout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addGroup(jDialogConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(tfURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addGroup(jDialogConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addGroup(jDialogConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(289, Short.MAX_VALUE)))
        );

        jDialogAddProduct.setBounds(new java.awt.Rectangle(0, 0, 400, 300));
        jDialogAddProduct.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jDialogAddProductWindowOpened(evt);
            }
        });

        jLabel4.setText("jLabel4");

        btnAddProduct.setText("Add");
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        tfAddCountProduct.setToolTipText("");

        jLabel8.setText("jLabel8");

        cbAddProductIdStorage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jDialogAddProductLayout = new javax.swing.GroupLayout(jDialogAddProduct.getContentPane());
        jDialogAddProduct.getContentPane().setLayout(jDialogAddProductLayout);
        jDialogAddProductLayout.setHorizontalGroup(
            jDialogAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddProductLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jDialogAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogAddProductLayout.createSequentialGroup()
                        .addGroup(jDialogAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(49, 49, 49)
                        .addGroup(jDialogAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfAddNameProduct)
                            .addComponent(tfAddCostProduct)
                            .addComponent(tfAddCountProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)))
                    .addGroup(jDialogAddProductLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(49, 49, 49)
                        .addComponent(cbAddProductIdStorage, 0, 121, Short.MAX_VALUE)))
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogAddProductLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        jDialogAddProductLayout.setVerticalGroup(
            jDialogAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddProductLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jDialogAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfAddNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfAddCostProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfAddCountProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbAddProductIdStorage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddProduct)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jTable1);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        BtnAdd.setText("Add");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        jMenu1.setText("Подключение к БД");

        jMenuItem1.setText("Создать подключение");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Отключиться");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Выход");
        jMenu1.add(jMenuItem3);

        menu.add(jMenu1);

        jMenu2.setText("Справочники");

        menuItemStorage.setText("storage");
        menuItemStorage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemStorageActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemStorage);

        menuItemProduct.setText("product");
        menuItemProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProductActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemProduct);

        jMenuItem6.setText("jMenuItem6");
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("jMenuItem7");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("jMenuItem8");
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("jMenuItem9");
        jMenu2.add(jMenuItem9);

        jMenuItem10.setText("jMenuItem10");
        jMenu2.add(jMenuItem10);

        menu.add(jMenu2);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(Label, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnAdd)
                        .addGap(26, 26, 26)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label)
                    .addComponent(BtnAdd)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jDialogConnection.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuItemStorageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemStorageActionPerformed
        if (!db.isFlag_connect()) {
            JOptionPane.showMessageDialog(this, "Connection error");
            return;
        }
        try {
            updateStorageTable();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
        selectedTable = "storage";
        
    }//GEN-LAST:event_menuItemStorageActionPerformed

    ///
    ///далее 7 одинковых методов для заполнения и вывода каждой таблицы
    ///
    private void updateStorageTable() throws SQLException {
        storageList = storageController.selectAll();
        Object[] mas = {"id_storage", "adress"};
        DefaultTableModel defModel = new DefaultTableModel(mas, 0);
        for (int i = 0; i < storageList.size(); i++) {
             defModel.addRow(storageList.get(i).getString());
        }
        jTable1.setModel(defModel);
    }
    private void updateProductTable() throws SQLException {
        productList = productController.selectAll();
        Object[] mas = {"id_product", "name", "cost", "count", "storage(fk)"};
        DefaultTableModel defModel = new DefaultTableModel(mas, 0);
        for (int i = 0; i < productList.size(); i++) {
             defModel.addRow(productList.get(i).getString());
        }
        jTable1.setModel(defModel);
    }
    
    
    
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
          switch (selectedTable) {
           case "storage" :
               Storage s = storageList.get(jTable1.getSelectedRow());
               
               try {
                   storageController.delete(s);
                   updateStorageTable();
               } catch (SQLException ex) {
                   //Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                   JOptionPane.showMessageDialog(this, "You can not delete this record - "
                           + "a violation of the integrity of the database");
               }
               break;
               
            default: 
            JOptionPane.showMessageDialog(this, "You cannot edit this table");
            break;
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void ConnectionOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectionOKActionPerformed
        try {
            db.createConnection(tfURL.getText(), tfName.getText(), tfPassword.getText());
            storageController = new StorageController(db.getConnection());
            productController = new ProductController(db.getConnection());
            ///
            ///+5 контроллеров других тут!!
            ///

            Label.setText("Connect");
            
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            ex.printStackTrace();
        }
        catch (ClassNotFoundException ex) {
            Logger.getLogger(ConnectionFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDialogConnection.setVisible(false);
        //dispose();
    }//GEN-LAST:event_ConnectionOKActionPerformed

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        switch (selectedTable) {
            case "storage" :
                Storage s = new Storage();
                s.setAdress(JOptionPane.showInputDialog(this, "Print adress"));
                try {
                    storageController.add(s);
                    updateStorageTable();
                } catch (SQLException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    ex.printStackTrace();
                }
                break;
            case "product" :
                jDialogAddProduct.setVisible(true);
                break;
            default: 
                JOptionPane.showMessageDialog(this, "You cannot edit this table");
                break;
        }
    }//GEN-LAST:event_BtnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        switch (selectedTable) {
           case "storage" :
               Storage s = storageList.get(jTable1.getSelectedRow());
               s.setAdress(JOptionPane.showInputDialog(this, "Print new adress"));
               try {
                   storageController.update(s);
                   updateStorageTable();
               } catch (SQLException ex) {
                   Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
               }
               break;
               
            default: 
            JOptionPane.showMessageDialog(this, "You cannot edit this table");
            break;
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        try {
            Product product = new Product();
            product.setCost(Integer.parseInt(tfAddCostProduct.getText()));
            product.setCount(Integer.parseInt(tfAddCountProduct.getText()));
            product.setName(tfAddNameProduct.getText());
            product.setId_storage(Integer.parseInt((String) cbAddProductIdStorage.getSelectedItem()));
            productController.add(product);
            
            jDialogConnection.setVisible(false);
            updateProductTable();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDialogAddProduct.setVisible(false);
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void menuItemProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProductActionPerformed
        if (!db.isFlag_connect()) {
            JOptionPane.showMessageDialog(this, "Connection error");
            return;
        }
        try {
            updateProductTable();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
        selectedTable = "product";
    }//GEN-LAST:event_menuItemProductActionPerformed

    private void jDialogAddProductWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialogAddProductWindowOpened
        try {
            fillCBProduct();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jDialogAddProductWindowOpened

    public void fillCBProduct() throws SQLException {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
       
        Object[] mas = storageController.getIds();
        for (int i = 0; i < mas.length; i++) {
            model.addElement(mas[i].toString());
            System.out.println(mas[i].toString());
        } 
        cbAddProductIdStorage.setModel(model);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton ConnectionOK;
    private javax.swing.JLabel Label;
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JComboBox<String> cbAddProductIdStorage;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialogAddProduct;
    private javax.swing.JDialog jDialogConnection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem menuItemProduct;
    private javax.swing.JMenuItem menuItemStorage;
    private javax.swing.JTextField tfAddCostProduct;
    private javax.swing.JTextField tfAddCountProduct;
    private javax.swing.JTextField tfAddNameProduct;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPassword;
    private javax.swing.JTextField tfURL;
    // End of variables declaration//GEN-END:variables
    
    DBManager db = new DBManager();
    StorageController storageController;
    ProductController productController;
    List<Storage> storageList;
    List<Product> productList;
    String selectedTable;
}
