package Frames;

import Controllers.CustomerController;
import Controllers.ProductController;
import Controllers.ProviderController;
import Controllers.StorageController;
import Controllers.SupplyController;
import Controllers.SupplyProductController;
import DB.DBManager;
import Entity.Customer;
import Entity.Product;
import Entity.Provider;
import Entity.Storage;
import Entity.Supply;
import Entity.SupplyProduct;
import java.sql.Date;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tanya
 */
public class MainFrame extends javax.swing.JFrame {
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogConnection = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ConnectionOK = new javax.swing.JButton();
        tfURL = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        tfPassword = new javax.swing.JTextField();
        jDialogAddProduct = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        btnAddProduct = new javax.swing.JButton();
        tfAddNameProduct = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfAddCostProduct = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfAddCountProduct = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbAddProductIdStorage = new javax.swing.JComboBox<>();
        jDialogAddCustomer = new javax.swing.JDialog();
        btnAddCustomer = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfNameCustomer = new javax.swing.JTextField();
        tfSurnamecustomer = new javax.swing.JTextField();
        tfAdressCustomer = new javax.swing.JTextField();
        jDialogEditProduct = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        tfEditCountProduct1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbEditProductIdStorage1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        btnEditProduct1 = new javax.swing.JButton();
        tfEditNameProduct1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfEditCostProduct1 = new javax.swing.JTextField();
        jDialogEditCustomer = new javax.swing.JDialog();
        tfEditNameCustomer1 = new javax.swing.JTextField();
        tfEditSurnamecustomer1 = new javax.swing.JTextField();
        tfEditAdressCustomer1 = new javax.swing.JTextField();
        btnEditCustomer1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jDialogAddProvider = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tfAddProviderName = new javax.swing.JTextField();
        tfAddProviderAdress = new javax.swing.JTextField();
        btnAddProvider = new javax.swing.JButton();
        jDialogEditProvider = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tfEditProviderName1 = new javax.swing.JTextField();
        tfEditProviderAdress1 = new javax.swing.JTextField();
        btnEditProvider1 = new javax.swing.JButton();
        jDialogSupply = new javax.swing.JDialog();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        cbIdProviderSupply = new javax.swing.JComboBox<>();
        tfCountSupply = new javax.swing.JTextField();
        tfDateSupply = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        cbIdProduct = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        btnAddSupply = new javax.swing.JButton();
        btnUpdateSupply = new javax.swing.JButton();
        btnDeleteSupply = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Label = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        BtnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemStorage = new javax.swing.JMenuItem();
        menuItemProduct = new javax.swing.JMenuItem();
        menuItemCustomer = new javax.swing.JMenuItem();
        menuItemProvider = new javax.swing.JMenuItem();
        menuItemSupply = new javax.swing.JMenuItem();
        menuItemSupplyProduct = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuItemAddSupply = new javax.swing.JMenuItem();
        menuItemAddSale = new javax.swing.JMenuItem();

        jDialogConnection.setBounds(new java.awt.Rectangle(0, 0, 500, 300));

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        ConnectionOK.setText("OK");
        ConnectionOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectionOKActionPerformed(evt);
            }
        });

        tfURL.setText("jdbc:postgresql://localhost:5432/storage");

        tfName.setText("postgres");

        tfPassword.setText("1");

        javax.swing.GroupLayout jDialogConnectionLayout = new javax.swing.GroupLayout(jDialogConnection.getContentPane());
        jDialogConnection.getContentPane().setLayout(jDialogConnectionLayout);
        jDialogConnectionLayout.setHorizontalGroup(
            jDialogConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogConnectionLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(ConnectionOK, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(377, Short.MAX_VALUE))
            .addGroup(jDialogConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogConnectionLayout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addGroup(jDialogConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1))
                    .addGap(34, 34, 34)
                    .addGroup(jDialogConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfPassword)
                        .addComponent(tfName)
                        .addComponent(tfURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(280, Short.MAX_VALUE)))
        );
        jDialogConnectionLayout.setVerticalGroup(
            jDialogConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogConnectionLayout.createSequentialGroup()
                .addContainerGap(420, Short.MAX_VALUE)
                .addComponent(ConnectionOK)
                .addContainerGap())
            .addGroup(jDialogConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogConnectionLayout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addGroup(jDialogConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(tfURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addGroup(jDialogConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addGroup(jDialogConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(289, Short.MAX_VALUE)))
        );

        jDialogAddProduct.setBounds(new java.awt.Rectangle(0, 0, 400, 300));
        jDialogAddProduct.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jDialogAddProductWindowOpened(evt);
            }
        });

        jLabel4.setText("Name");

        btnAddProduct.setText("Add");
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        jLabel5.setText("Cost");

        jLabel6.setText("Count");

        tfAddCountProduct.setToolTipText("");

        jLabel8.setText("Id_storage");

        cbAddProductIdStorage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jDialogAddProductLayout = new javax.swing.GroupLayout(jDialogAddProduct.getContentPane());
        jDialogAddProduct.getContentPane().setLayout(jDialogAddProductLayout);
        jDialogAddProductLayout.setHorizontalGroup(
            jDialogAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddProductLayout.createSequentialGroup()
                .addGroup(jDialogAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogAddProductLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jDialogAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(25, 25, 25)
                        .addGroup(jDialogAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfAddNameProduct)
                            .addComponent(tfAddCostProduct)
                            .addComponent(tfAddCountProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(cbAddProductIdStorage, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jDialogAddProductLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jDialogAddProductLayout.setVerticalGroup(
            jDialogAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddProductLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jDialogAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfAddNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfAddCostProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfAddCountProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbAddProductIdStorage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnAddProduct)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jDialogAddCustomer.setBounds(new java.awt.Rectangle(0, 0, 400, 300));

        btnAddCustomer.setText("Add");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });

        jLabel7.setText("Name");

        jLabel9.setText("Surname");

        jLabel10.setText("Adress");

        javax.swing.GroupLayout jDialogAddCustomerLayout = new javax.swing.GroupLayout(jDialogAddCustomer.getContentPane());
        jDialogAddCustomer.getContentPane().setLayout(jDialogAddCustomerLayout);
        jDialogAddCustomerLayout.setHorizontalGroup(
            jDialogAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddCustomerLayout.createSequentialGroup()
                .addGroup(jDialogAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogAddCustomerLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btnAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialogAddCustomerLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jDialogAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(36, 36, 36)
                        .addGroup(jDialogAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfAdressCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSurnamecustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNameCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jDialogAddCustomerLayout.setVerticalGroup(
            jDialogAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogAddCustomerLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jDialogAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfNameCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jDialogAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfSurnamecustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jDialogAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfAdressCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnAddCustomer)
                .addGap(39, 39, 39))
        );

        jDialogEditProduct.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jDialogEditProductWindowOpened(evt);
            }
        });

        jLabel11.setText("Count");

        tfEditCountProduct1.setToolTipText("");

        jLabel12.setText("Id_storage");

        cbEditProductIdStorage1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel13.setText("Name");

        btnEditProduct1.setText("Edit");
        btnEditProduct1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProduct1ActionPerformed(evt);
            }
        });

        jLabel14.setText("Cost");

        javax.swing.GroupLayout jDialogEditProductLayout = new javax.swing.GroupLayout(jDialogEditProduct.getContentPane());
        jDialogEditProduct.getContentPane().setLayout(jDialogEditProductLayout);
        jDialogEditProductLayout.setHorizontalGroup(
            jDialogEditProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditProductLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jDialogEditProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogEditProductLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnEditProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162))
                    .addGroup(jDialogEditProductLayout.createSequentialGroup()
                        .addGroup(jDialogEditProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(25, 25, 25)
                        .addGroup(jDialogEditProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfEditNameProduct1)
                            .addComponent(tfEditCostProduct1)
                            .addComponent(tfEditCountProduct1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(cbEditProductIdStorage1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jDialogEditProductLayout.setVerticalGroup(
            jDialogEditProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditProductLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jDialogEditProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tfEditNameProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogEditProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfEditCostProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogEditProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfEditCountProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogEditProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbEditProductIdStorage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnEditProduct1)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jDialogEditCustomer.setBounds(new java.awt.Rectangle(0, 0, 400, 300));

        btnEditCustomer1.setText("Edit");
        btnEditCustomer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCustomer1ActionPerformed(evt);
            }
        });

        jLabel15.setText("Name");

        jLabel16.setText("Surname");

        jLabel17.setText("Adress");

        javax.swing.GroupLayout jDialogEditCustomerLayout = new javax.swing.GroupLayout(jDialogEditCustomer.getContentPane());
        jDialogEditCustomer.getContentPane().setLayout(jDialogEditCustomerLayout);
        jDialogEditCustomerLayout.setHorizontalGroup(
            jDialogEditCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditCustomerLayout.createSequentialGroup()
                .addGroup(jDialogEditCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogEditCustomerLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jDialogEditCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(36, 36, 36)
                        .addGroup(jDialogEditCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfEditAdressCustomer1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEditSurnamecustomer1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEditNameCustomer1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDialogEditCustomerLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btnEditCustomer1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jDialogEditCustomerLayout.setVerticalGroup(
            jDialogEditCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogEditCustomerLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jDialogEditCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tfEditNameCustomer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jDialogEditCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tfEditSurnamecustomer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jDialogEditCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tfEditAdressCustomer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnEditCustomer1)
                .addGap(29, 29, 29))
        );

        jDialogAddProvider.setBounds(new java.awt.Rectangle(0, 0, 300, 200));

        jLabel18.setText("Name of company");

        jLabel19.setText("Adress");

        btnAddProvider.setText("Add");
        btnAddProvider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProviderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogAddProviderLayout = new javax.swing.GroupLayout(jDialogAddProvider.getContentPane());
        jDialogAddProvider.getContentPane().setLayout(jDialogAddProviderLayout);
        jDialogAddProviderLayout.setHorizontalGroup(
            jDialogAddProviderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddProviderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogAddProviderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jDialogAddProviderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfAddProviderName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAddProviderAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
            .addGroup(jDialogAddProviderLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(btnAddProvider, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogAddProviderLayout.setVerticalGroup(
            jDialogAddProviderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddProviderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogAddProviderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tfAddProviderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jDialogAddProviderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tfAddProviderAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnAddProvider)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDialogEditProvider.setBounds(new java.awt.Rectangle(0, 0, 300, 200));

        jLabel20.setText("Name of company");

        jLabel21.setText("Adress");

        btnEditProvider1.setText("Edit");
        btnEditProvider1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProvider1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogEditProviderLayout = new javax.swing.GroupLayout(jDialogEditProvider.getContentPane());
        jDialogEditProvider.getContentPane().setLayout(jDialogEditProviderLayout);
        jDialogEditProviderLayout.setHorizontalGroup(
            jDialogEditProviderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditProviderLayout.createSequentialGroup()
                .addGroup(jDialogEditProviderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogEditProviderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDialogEditProviderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(60, 60, 60)
                        .addGroup(jDialogEditProviderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfEditProviderName1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEditProviderAdress1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDialogEditProviderLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btnEditProvider1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jDialogEditProviderLayout.setVerticalGroup(
            jDialogEditProviderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditProviderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogEditProviderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tfEditProviderName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jDialogEditProviderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tfEditProviderAdress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEditProvider1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jDialogSupply.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jDialogSupplyWindowOpened(evt);
            }
        });

        jLabel22.setText("Count");

        jLabel23.setText("SupplyDate");

        jLabel24.setText("IdProvider");

        cbIdProviderSupply.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel25.setText("idProduct");

        cbIdProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAddSupply.setText("Add");
        btnAddSupply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSupplyActionPerformed(evt);
            }
        });

        btnUpdateSupply.setText("Update");
        btnUpdateSupply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateSupplyActionPerformed(evt);
            }
        });

        btnDeleteSupply.setText("Delete");
        btnDeleteSupply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSupplyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogSupplyLayout = new javax.swing.GroupLayout(jDialogSupply.getContentPane());
        jDialogSupply.getContentPane().setLayout(jDialogSupplyLayout);
        jDialogSupplyLayout.setHorizontalGroup(
            jDialogSupplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogSupplyLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jDialogSupplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23)
                    .addGroup(jDialogSupplyLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel22)))
                .addGap(34, 34, 34)
                .addGroup(jDialogSupplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCountSupply, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbIdProviderSupply, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDateSupply, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDialogSupplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogSupplyLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogSupplyLayout.createSequentialGroup()
                        .addComponent(cbIdProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
            .addGroup(jDialogSupplyLayout.createSequentialGroup()
                .addGroup(jDialogSupplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogSupplyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialogSupplyLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btnAddSupply)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateSupply)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteSupply)))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jDialogSupplyLayout.setVerticalGroup(
            jDialogSupplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogSupplyLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jDialogSupplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tfCountSupply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGroup(jDialogSupplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogSupplyLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jDialogSupplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(tfDateSupply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jDialogSupplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(cbIdProviderSupply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDialogSupplyLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbIdProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogSupplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddSupply)
                    .addComponent(btnUpdateSupply)
                    .addComponent(btnDeleteSupply))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jTable1);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        BtnAdd.setText("Add");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        jMenu1.setText("Подключение к БД");

        jMenuItem1.setText("Создать подключение");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Отключиться");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Выход");
        jMenu1.add(jMenuItem3);

        menu.add(jMenu1);

        jMenu2.setText("Справочники");

        menuItemStorage.setText("storage");
        menuItemStorage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemStorageActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemStorage);

        menuItemProduct.setText("product");
        menuItemProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProductActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemProduct);

        menuItemCustomer.setText("customer");
        menuItemCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCustomerActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemCustomer);

        menuItemProvider.setText("provider");
        menuItemProvider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProviderActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemProvider);

        menuItemSupply.setText("supply");
        menuItemSupply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSupplyActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemSupply);

        menuItemSupplyProduct.setText("supply_product");
        menuItemSupplyProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSupplyProductActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemSupplyProduct);

        jMenuItem10.setText("jMenuItem10");
        jMenu2.add(jMenuItem10);

        menu.add(jMenu2);

        jMenu3.setText("Действия");

        menuItemAddSupply.setText("Добавить поставку");
        menuItemAddSupply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddSupplyActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemAddSupply);

        menuItemAddSale.setText("Добавить продажу");
        jMenu3.add(menuItemAddSale);

        menu.add(jMenu3);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(Label, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnAdd)
                        .addGap(26, 26, 26)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label)
                    .addComponent(BtnAdd)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jDialogConnection.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuItemStorageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemStorageActionPerformed
        if (!db.isFlag_connect()) {
            JOptionPane.showMessageDialog(this, "Connection error");
            return;
        }
        try {
            updateStorageTable();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
        selectedTable = "storage";
        
    }//GEN-LAST:event_menuItemStorageActionPerformed

    ///
    ///далее 7 одинковых методов для заполнения и вывода каждой таблицы
    ///
    private void updateStorageTable() throws SQLException {
        storageList = storageController.selectAll();
        Object[] mas = {"id_storage", "adress"};
        DefaultTableModel defModel = new DefaultTableModel(mas, 0);
        for (int i = 0; i < storageList.size(); i++) {
             defModel.addRow(storageList.get(i).getString());
        }
        jTable1.setModel(defModel);
    }
    private void updateProductTable() throws SQLException {
        productList = productController.selectAll();
        Object[] mas = {"id_product", "name", "cost", "count", "storage(fk)"};
        DefaultTableModel defModel = new DefaultTableModel(mas, 0);
        for (int i = 0; i < productList.size(); i++) {
             defModel.addRow(productList.get(i).getString());
        }
        jTable1.setModel(defModel);
    }
    private void updateCustomerTable() throws SQLException {
        customerList = customerController.selectAll();
        Object[] mas = {"id_customer", "name", "surname", "adress"};
        DefaultTableModel defModel = new DefaultTableModel(mas, 0);
        for (int i = 0; i < customerList.size(); i++) {
             defModel.addRow(customerList.get(i).getString());
        }
        jTable1.setModel(defModel);
    }
    private void updateProviderTable() throws SQLException {
        providerList = providerController.selectAll();
        Object[] mas = {"id_provider", "name of company", "adress"};
        DefaultTableModel defModel = new DefaultTableModel(mas, 0);
        for (int i = 0; i < providerList.size(); i++) {
             defModel.addRow(providerList.get(i).getString());
        }
        jTable1.setModel(defModel);
    }
    private void updateSupplyTable() throws SQLException {
        supplyList = supplyController.selectAll();
        Object[] mas = {"id_supply", "count", "supply_date", "id_provider"};
        DefaultTableModel defModel = new DefaultTableModel(mas, 0);
        for (int i = 0; i < supplyList.size(); i++) {
             defModel.addRow(supplyList.get(i).getString());
        }
        jTable1.setModel(defModel);
    }
    private void updateSupplyProductTable() throws SQLException {
        supplyProductList = supplyProductController.selectAll();
        Object[] mas = {"id_supply", "id_product"};
        DefaultTableModel defModel = new DefaultTableModel(mas, 0);
        for (int i = 0; i < supplyProductList.size(); i++) {
             defModel.addRow(supplyProductList.get(i).getString());
        }
        jTable1.setModel(defModel);
    }
    
    
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        switch (selectedTable) {
            case "storage" :
               Storage s = storageList.get(jTable1.getSelectedRow());
               
                try {
                   storageController.delete(s);
                   updateStorageTable();
                } catch (SQLException ex) {
                   //Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                   JOptionPane.showMessageDialog(this, "You can not delete this record - "
                           + "a violation of the integrity of the database");
                }
                break;
            case "product" :
                Product p = productList.get(jTable1.getSelectedRow());
                try{
                    productController.delete(p);
                    updateProductTable();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "You can not delete this record - "
                           + "a violation of the integrity of the database");
                }
                break;
            case "customer" :
                Customer c = customerList.get(jTable1.getSelectedRow());
                 try{
                    customerController.delete(c);
                    updateCustomerTable();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "You can not delete this record - "
                           + "a violation of the integrity of the database");
                }
                break;
            case "provider" :
                Provider pr = providerList.get(jTable1.getSelectedRow());
                 try{
                    providerController.delete(pr);
                    updateProviderTable();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "You can not delete this record - "
                           + "a violation of the integrity of the database");
                }
                break;
            default: 
            JOptionPane.showMessageDialog(this, "You cannot edit this table");
            break;
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void ConnectionOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectionOKActionPerformed
        try {
            db.createConnection(tfURL.getText(), tfName.getText(), tfPassword.getText());
            storageController = new StorageController(db.getConnection());
            productController = new ProductController(db.getConnection());
            customerController = new CustomerController(db.getConnection());
            providerController = new ProviderController(db.getConnection());
            supplyController = new SupplyController(db.getConnection());
            supplyProductController = new SupplyProductController(db.getConnection());
            ///
            ///+1 контроллер другой тут!!
            ///

            Label.setText("Connect");
            
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            ex.printStackTrace();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDialogConnection.setVisible(false);
        //dispose();
    }//GEN-LAST:event_ConnectionOKActionPerformed

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        switch (selectedTable) {
            case "storage" :
                Storage s = new Storage();
                s.setAdress(JOptionPane.showInputDialog(this, "Print adress"));
                try {
                    storageController.add(s);
                    updateStorageTable();
                } catch (SQLException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    ex.printStackTrace();
                }
                break;
            case "product" :
                jDialogAddProduct.setVisible(true);
                break;
            case "customer" :
                jDialogAddCustomer.setVisible(true);
                break;
            case "provider" :
                jDialogAddProvider.setVisible(true);
                break;
            default: 
                JOptionPane.showMessageDialog(this, "You cannot edit this table");
                break;
        }
    }//GEN-LAST:event_BtnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        switch (selectedTable) {
            case "storage" :
                Storage s = storageList.get(jTable1.getSelectedRow());
                s.setAdress(JOptionPane.showInputDialog(this, "Print new adress"));
                try {
                    storageController.update(s);
                    updateStorageTable();
                } catch (SQLException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
            case "product" :
                jDialogEditProduct.setVisible(true);
                break;
            case "customer" :
                jDialogEditCustomer.setVisible(true);
                break;
            case "provider" :
                jDialogEditProvider.setVisible(true);
                break;
            default: 
            JOptionPane.showMessageDialog(this, "You cannot edit this table");
            break;
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        try {
            Product product = new Product();
            product.setCost(Integer.parseInt(tfAddCostProduct.getText()));
            product.setCount(Integer.parseInt(tfAddCountProduct.getText()));
            product.setName(tfAddNameProduct.getText());
            product.setId_storage(Integer.parseInt((String) cbAddProductIdStorage.getSelectedItem()));
            productController.add(product);
            updateProductTable();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDialogAddProduct.setVisible(false);
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void menuItemProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProductActionPerformed
        if (!db.isFlag_connect()) {
            JOptionPane.showMessageDialog(this, "Connection error");
            return;
        }
        try {
            updateProductTable();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
        selectedTable = "product";
    }//GEN-LAST:event_menuItemProductActionPerformed

    private void jDialogAddProductWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialogAddProductWindowOpened
        try {
            fillCBProduct();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jDialogAddProductWindowOpened

    private void menuItemCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCustomerActionPerformed
        if (!db.isFlag_connect()) {
            JOptionPane.showMessageDialog(this, "Connection error");
            return;
        }
        try {
            updateCustomerTable();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
        selectedTable = "customer";
    }//GEN-LAST:event_menuItemCustomerActionPerformed

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed
        try {
            Customer customer = new Customer();
            customer.setSurname(tfSurnamecustomer.getText());
            customer.setAdress(tfAdressCustomer.getText());
            customer.setName(tfNameCustomer.getText()); 
            customerController.add(customer);
            updateCustomerTable();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDialogAddCustomer.setVisible(false);
    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void btnEditProduct1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProduct1ActionPerformed
        try {
            Product p = productList.get(jTable1.getSelectedRow());
            p.setCost(Integer.parseInt(tfEditCostProduct1.getText()));
            p.setCount(Integer.parseInt(tfEditCountProduct1.getText()));
            p.setName(tfEditNameProduct1.getText());
            p.setId_storage(Integer.parseInt((String) cbEditProductIdStorage1.getSelectedItem()));
            productController.update(p);
            updateProductTable();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDialogEditProduct.setVisible(false);
    }//GEN-LAST:event_btnEditProduct1ActionPerformed

    private void btnEditCustomer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCustomer1ActionPerformed
         try {
            Customer customer = customerList.get(jTable1.getSelectedRow());
            customer.setSurname(tfEditSurnamecustomer1.getText());
            customer.setAdress(tfEditAdressCustomer1.getText());
            customer.setName(tfEditNameCustomer1.getText()); 
            customerController.update(customer);
            updateCustomerTable();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDialogEditCustomer.setVisible(false);
    }//GEN-LAST:event_btnEditCustomer1ActionPerformed

    private void jDialogEditProductWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialogEditProductWindowOpened
        try {
            fillCBProduct();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jDialogEditProductWindowOpened

    private void btnAddProviderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProviderActionPerformed
        try {
            Provider provider = new Provider();
            provider.setNameOfCompany(tfAddProviderName.getText());
            provider.setAdress(tfAddProviderAdress.getText());
            providerController.add(provider);
            updateProviderTable();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDialogAddProvider.setVisible(false);
    }//GEN-LAST:event_btnAddProviderActionPerformed

    private void menuItemProviderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProviderActionPerformed
        if (!db.isFlag_connect()) {
            JOptionPane.showMessageDialog(this, "Connection error");
            return;
        }
        try {
            updateProviderTable();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
        selectedTable = "provider";
    }//GEN-LAST:event_menuItemProviderActionPerformed

    private void btnEditProvider1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProvider1ActionPerformed
        try {
            Provider provider = providerList.get(jTable1.getSelectedRow());
            provider.setNameOfCompany(tfEditProviderName1.getText());
            provider.setAdress(tfEditProviderAdress1.getText());
            providerController.update(provider);
            updateProviderTable();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDialogEditProvider.setVisible(false);
    }//GEN-LAST:event_btnEditProvider1ActionPerformed

    private void menuItemSupplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSupplyActionPerformed
        if (!db.isFlag_connect()) {
            JOptionPane.showMessageDialog(this, "Connection error");
            return;
        }
        try {
            updateSupplyTable();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
        selectedTable = "supply";
    }//GEN-LAST:event_menuItemSupplyActionPerformed

    private void menuItemAddSupplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddSupplyActionPerformed
        jDialogSupply.setVisible(true);
    }//GEN-LAST:event_menuItemAddSupplyActionPerformed

    private void btnAddSupplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSupplyActionPerformed
        try {
            Supply supply = new Supply();
            supply.setCount(Integer.parseInt(tfCountSupply.getText()));
            supply.setSupplyDate(Date.valueOf(tfDateSupply.getText()));
            supply.setIdProvider(Integer.parseInt((String) cbIdProviderSupply.getSelectedItem()));
            supplyController.add(supply);
            updateSupplyTable();
            
            SupplyProduct suppyProduct = new SupplyProduct();
            suppyProduct.setIdSupply(supplyController.getLastIdSupply());
            suppyProduct.setIdProduct(Integer.parseInt((String) cbIdProduct.getSelectedItem()));
            supplyProductController.add(suppyProduct);
            updateSupplyProductTable();
            
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnAddSupplyActionPerformed

    private void jDialogSupplyWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialogSupplyWindowOpened
        try {
            fillCBProviderSupply();
            fillCBProductinSupply();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jDialogSupplyWindowOpened

    private void menuItemSupplyProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSupplyProductActionPerformed
        if (!db.isFlag_connect()) {
            JOptionPane.showMessageDialog(this, "Connection error");
            return;
        }
        try {
            updateSupplyProductTable();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
        selectedTable = "supplyProduct";
    }//GEN-LAST:event_menuItemSupplyProductActionPerformed

    private void btnUpdateSupplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateSupplyActionPerformed
        try {
            Supply supply = supplyList.get(jTable1.getSelectedRow());
            supply.setCount(Integer.parseInt(tfCountSupply.getText()));
            supply.setSupplyDate(Date.valueOf(tfDateSupply.getText()));
            supply.setIdProvider(Integer.parseInt((String) cbIdProviderSupply.getSelectedItem()));
            supplyController.update(supply);
            updateSupplyTable();
            
            SupplyProduct suppyProduct = supplyProductController.selectByIndex(jTable1.getSelectedRow());
            suppyProduct.setIdSupply(supply.getIdSupply());
            suppyProduct.setIdProduct(Integer.parseInt((String) cbIdProduct.getSelectedItem()));
            supplyProductController.update(suppyProduct);
            updateSupplyProductTable();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateSupplyActionPerformed

    private void btnDeleteSupplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSupplyActionPerformed
        try{
            Supply s = supplyList.get(jTable1.getSelectedRow());
            SupplyProduct suppyProduct = supplyProductController.selectByIndex(s.getIdSupply());
            
            supplyProductController.delete(suppyProduct);
            supplyController.delete(s);
            updateSupplyTable();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "You can not delete this record - "
                   + "a violation of the integrity of the database");
        }
    }//GEN-LAST:event_btnDeleteSupplyActionPerformed

    public void fillCBProduct() throws SQLException {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
       
        Object[] mas = storageController.getIds();
        for (int i = 0; i < mas.length; i++) {
            model.addElement(mas[i].toString());
            System.out.println(mas[i].toString());
        } 
        cbAddProductIdStorage.setModel(model);
        cbEditProductIdStorage1.setModel(model);
    }
    public void fillCBProviderSupply() throws SQLException {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
       
        Object[] mas = providerController.getIds();
        for (int i = 0; i < mas.length; i++) {
            model.addElement(mas[i].toString());
            System.out.println(mas[i].toString());
        } 
        cbIdProviderSupply.setModel(model);
    }
    public void fillCBProductinSupply() throws SQLException {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
       
        Object[] mas = productController.getIds();
        for (int i = 0; i < mas.length; i++) {
            model.addElement(mas[i].toString());
            System.out.println(mas[i].toString());
        } 
        cbIdProduct.setModel(model);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton ConnectionOK;
    private javax.swing.JLabel Label;
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnAddProvider;
    private javax.swing.JButton btnAddSupply;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteSupply;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEditCustomer1;
    private javax.swing.JButton btnEditProduct1;
    private javax.swing.JButton btnEditProvider1;
    private javax.swing.JButton btnUpdateSupply;
    private javax.swing.JComboBox<String> cbAddProductIdStorage;
    private javax.swing.JComboBox<String> cbEditProductIdStorage1;
    private javax.swing.JComboBox<String> cbIdProduct;
    private javax.swing.JComboBox<String> cbIdProviderSupply;
    private javax.swing.JDialog jDialogAddCustomer;
    private javax.swing.JDialog jDialogAddProduct;
    private javax.swing.JDialog jDialogAddProvider;
    private javax.swing.JDialog jDialogConnection;
    private javax.swing.JDialog jDialogEditCustomer;
    private javax.swing.JDialog jDialogEditProduct;
    private javax.swing.JDialog jDialogEditProvider;
    private javax.swing.JDialog jDialogSupply;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem menuItemAddSale;
    private javax.swing.JMenuItem menuItemAddSupply;
    private javax.swing.JMenuItem menuItemCustomer;
    private javax.swing.JMenuItem menuItemProduct;
    private javax.swing.JMenuItem menuItemProvider;
    private javax.swing.JMenuItem menuItemStorage;
    private javax.swing.JMenuItem menuItemSupply;
    private javax.swing.JMenuItem menuItemSupplyProduct;
    private javax.swing.JTextField tfAddCostProduct;
    private javax.swing.JTextField tfAddCountProduct;
    private javax.swing.JTextField tfAddNameProduct;
    private javax.swing.JTextField tfAddProviderAdress;
    private javax.swing.JTextField tfAddProviderName;
    private javax.swing.JTextField tfAdressCustomer;
    private javax.swing.JTextField tfCountSupply;
    private javax.swing.JTextField tfDateSupply;
    private javax.swing.JTextField tfEditAdressCustomer1;
    private javax.swing.JTextField tfEditCostProduct1;
    private javax.swing.JTextField tfEditCountProduct1;
    private javax.swing.JTextField tfEditNameCustomer1;
    private javax.swing.JTextField tfEditNameProduct1;
    private javax.swing.JTextField tfEditProviderAdress1;
    private javax.swing.JTextField tfEditProviderName1;
    private javax.swing.JTextField tfEditSurnamecustomer1;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfNameCustomer;
    private javax.swing.JTextField tfPassword;
    private javax.swing.JTextField tfSurnamecustomer;
    private javax.swing.JTextField tfURL;
    // End of variables declaration//GEN-END:variables
    
    DBManager db = new DBManager();
    StorageController storageController;
    ProductController productController;
    CustomerController customerController;
    ProviderController providerController;
    SupplyController supplyController;
    SupplyProductController supplyProductController;
    List<Storage> storageList;
    List<Product> productList;
    List<Customer> customerList;
    List<Provider> providerList;
    List<Supply> supplyList;
    List<SupplyProduct> supplyProductList;
    String selectedTable;
}
